# Generated by Django 4.2.16 on 2024-11-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ente', models.CharField(default='', max_length=200, verbose_name='Ente')),
                ('acronimo', models.CharField(default='', max_length=200, verbose_name='Acronimo')),
                ('abscrito', models.CharField(default='', max_length=200, verbose_name='Abscritos')),
                ('responsable', models.CharField(default='', max_length=200, verbose_name='Responsable')),
                ('cargo', models.CharField(default='', max_length=200, verbose_name='Cargo')),
                ('telefono', models.CharField(default='', max_length=200, verbose_name='Telefono')),
                ('correo', models.CharField(default='', max_length=200, verbose_name='Correo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=200, verbose_name='Empresa')),
                ('responsable', models.CharField(default='', max_length=200, verbose_name='Responsable')),
                ('telefono', models.CharField(default='', max_length=200, verbose_name='Telefono')),
                ('correo', models.CharField(default='', max_length=200, verbose_name='Correo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gobierno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ente', models.CharField(default='', max_length=200, verbose_name='Ente')),
                ('acronimo', models.CharField(default='', max_length=200, verbose_name='Acronimo')),
                ('responsable', models.CharField(default='', max_length=200, verbose_name='Responsable')),
                ('cargo', models.CharField(default='', max_length=200, verbose_name='Cargo')),
                ('telefono', models.CharField(default='', max_length=200, verbose_name='Telefono')),
                ('correo', models.CharField(default='', max_length=200, verbose_name='Correo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministerio', models.CharField(default='', max_length=200, verbose_name='Ministerio')),
                ('acronimo', models.CharField(default='', max_length=200, verbose_name='Acronimo')),
                ('responsable', models.CharField(default='', max_length=200, verbose_name='Responsable')),
                ('cargo', models.CharField(default='', max_length=200, verbose_name='Cargo')),
                ('telefono', models.CharField(default='', max_length=200, verbose_name='Telefono')),
                ('correo', models.CharField(default='', max_length=200, verbose_name='Correo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=200, verbose_name='Empresa')),
                ('asn', models.CharField(default='', max_length=10, verbose_name='Asn:')),
                ('responsable', models.CharField(default='', max_length=200, verbose_name='Responsable')),
                ('telefono', models.CharField(default='', max_length=200, verbose_name='Telefono')),
                ('correo', models.CharField(default='', max_length=200, verbose_name='Correo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
