# Generated by Django 5.1.3 on 2024-12-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscritos',
            name='ente',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Ente'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='empresa',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='gobierno',
            name='ente',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Ente'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='ministerio',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Ministerio'),
        ),
        migrations.AlterField(
            model_name='privados',
            name='empresa',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='privados',
            name='responsable',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Responsable'),
        ),
    ]
