# Generated by Django 5.1.5 on 2025-01-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_abscritos_ente_alter_cert_empresa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gobierno',
            new_name='Agenda',
        ),
        migrations.DeleteModel(
            name='Abscritos',
        ),
        migrations.DeleteModel(
            name='Cert',
        ),
        migrations.DeleteModel(
            name='Ministerio',
        ),
        migrations.DeleteModel(
            name='Privados',
        ),
    ]
