# Generated by Django 5.1.6 on 2025-04-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_rename_gobierno_agenda_delete_abscritos_delete_cert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='correo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Teléfono'),
        ),
    ]
