# Generated by Django 5.2.3 on 2025-06-17 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_unique_together_chatroom_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre de la sala (para chats generales/de grupo).', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('room_type', 'general')), fields=('room_type', 'name'), name='unique_general_room_name'),
        ),
    ]
