# Generated by Django 5.2.3 on 2025-06-22 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_timestamp'),
        ('publicaciones', '0014_alter_recursos_pagos_cedula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo de Lectura',
                'verbose_name_plural': 'Recibos de Lectura',
                'unique_together': {('user', 'message')},
            },
        ),
        migrations.CreateModel(
            name='ResourceViewReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='publicaciones.recursos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_view_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo de Vista de Recurso',
                'verbose_name_plural': 'Recibos de Vista de Recursos',
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
