# Generated by Django 5.2.3 on 2025-06-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_readreceipt_resourceviewreceipt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourceviewreceipt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resourceviewreceipt',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourceviewreceipt',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReadReceipt',
        ),
        migrations.DeleteModel(
            name='ResourceViewReceipt',
        ),
    ]
