# Generated by Django 5.1.5 on 2025-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(default='', max_length=200, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='', max_length=200, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(default='', max_length=200, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Usuario'),
        ),
    ]
