# Generated by Django 5.1.6 on 2025-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_apellido_alter_usuarios_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(default='', max_length=200, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='correo',
            field=models.CharField(default='', max_length=200, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(default='', max_length=200, verbose_name='Teléfono'),
        ),
    ]
