# Generated by Django 5.1.6 on 2025-04-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_cargo_usuarios_correo_usuarios_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Correo'),
        ),
    ]
