# Generated by Django 5.1.6 on 2025-06-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarios_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='cargo',
        ),
    ]
