# Generated by Django 5.2.3 on 2025-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuarios_comunidad_usuarios_foto_usuarios_jefe_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
