# Generated by Django 5.2.3 on 2025-06-19 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuarios_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='jefe_calle',
        ),
    ]
