# Generated by Django 5.2.3 on 2025-06-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_usuarios_jefe_calle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Cédula'),
        ),
    ]
