# Generated by Django 5.2.3 on 2025-06-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_usuarios_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidad', models.CharField(default='', max_length=200, unique=True, verbose_name='comunidad')),
            ],
        ),
    ]
