# Generated by Django 5.2.3 on 2025-06-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_comunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.FileField(blank=True, default='', upload_to='fotos/', verbose_name='Imagen'),
        ),
    ]
