# Generated by Django 5.2.3 on 2025-06-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.FileField(default='', upload_to='fotos/', verbose_name='Imagen'),
        ),
    ]
