# Generated by Django 5.2.3 on 2025-06-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
