# Generated by Django 5.2.3 on 2025-06-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.CharField(default='', max_length=5000, verbose_name='Descripción'),
        ),
    ]
