# Generated by Django 5.2.3 on 2025-06-19 13:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_noticias_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(default='', max_length=200, verbose_name='Recurso')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha Aprobado')),
                ('pago', models.BooleanField(default=False)),
                ('precio', models.DateTimeField(blank=True, max_length=200, verbose_name='Precio')),
                ('estatus', models.CharField(default='', max_length=200, verbose_name='Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('servicio', models.CharField(default='', max_length=200, verbose_name='Servicio')),
                ('latitud', models.CharField(default='', max_length=200, verbose_name='Latitud')),
                ('longitud', models.CharField(default='', max_length=5000, verbose_name='Longitud')),
            ],
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.CharField(blank=True, default='', max_length=5000, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='Recursos_Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=200)),
                ('cedula', models.CharField(default='', max_length=50)),
                ('comunidad', models.CharField(default='', max_length=200)),
                ('comprbante', models.FileField(default='', upload_to='comprobantes/', verbose_name='Comprobante de Pago')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='publicaciones.recursos')),
            ],
        ),
    ]
