# Generated by Django 5.2.3 on 2025-06-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_recursos_servicios_alter_noticias_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.FileField(blank=True, default='', null=True, upload_to='fotos/', verbose_name='Imagen'),
        ),
    ]
