# Generated by Django 5.2.3 on 2025-06-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_alter_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='pago',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
