# Generated by Django 5.2.3 on 2025-06-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_alter_recursos_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='estatus',
            field=models.CharField(default='ACTIVO', max_length=200, verbose_name='Estatus'),
        ),
    ]
