# Generated by Django 5.2.3 on 2025-06-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_alter_recursos_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
