# Generated by Django 5.2.3 on 2025-06-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_alter_recursos_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursos_pagos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='recursos_pagos',
            name='apellido',
            field=models.CharField(default='', max_length=200, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='recursos_pagos',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='recursos_pagos',
            name='cedula',
            field=models.CharField(default='', max_length=50, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='recursos_pagos',
            name='comunidad',
            field=models.CharField(default='', max_length=200, verbose_name='Comunidad'),
        ),
    ]
