# Generated by Django 5.2.3 on 2025-06-20 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_remove_recursos_pagos_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Pago'),
        ),
    ]
