# Generated by Django 5.2.3 on 2025-06-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_alter_recursos_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursos_pagos',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='recursos_pagos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='recursos_pagos',
            name='usuario',
            field=models.CharField(default='', max_length=200, verbose_name='Usuario'),
        ),
    ]
