# Generated by Django 5.2.3 on 2025-06-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0010_remove_recursos_pagos_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='lugar',
            field=models.CharField(default='', max_length=200, verbose_name='Lugar'),
        ),
    ]
