# Generated by Django 5.2.3 on 2025-06-20 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_recursos_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos_pagos',
            name='fechap',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Fecha Pago'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Fecha Pago'),
        ),
    ]
