# Generated by Django 5.2.3 on 2025-06-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0012_recursos_pagos_fechap_alter_recursos_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursos_pagos',
            old_name='comprbante',
            new_name='comprobante',
        ),
    ]
