# Generated by Django 5.2.3 on 2025-06-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0013_rename_comprbante_recursos_pagos_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos_pagos',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='recursos_pagos',
            name='comunidad',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Comunidad'),
        ),
        migrations.AlterField(
            model_name='recursos_pagos',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Usuario'),
        ),
    ]
